from django.contrib.auth import get_user_model
from django.utils.translation import ugettext as _
from rest_framework import exceptions
from rest_framework_jwt.authentication import JSONWebTokenAuthentication

class NarralyJSONWebTokenAuthentication(JSONWebTokenAuthentication):
    '''
    Authentication strategy that uses JWT but does not check with Django user management to see if
    the user exists. We simply check that the token is valid and contains a user ID, and assume that
    the tokens are generated by another service.
    '''
    def authenticate_credentials(self, payload):
        # To ensure compatibility with other middlewares, we create our own User, even though it is
        # not stored by Django.
        User = get_user_model()
        username = payload.get('sub')

        if not username:
            msg = _('Invalid payload.')
            raise exceptions.AuthenticationFailed(msg)

        return User(username=username)
